<?php

/**
 * BaseBreed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Dog
 * 
 * @method integer             getId()   Returns the current record's "id" value
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getDog()  Returns the current record's "Dog" collection
 * @method Breed               setId()   Sets the current record's "id" value
 * @method Breed               setName() Sets the current record's "name" value
 * @method Breed               setDog()  Sets the current record's "Dog" collection
 * 
 * @package    petgroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBreed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('breed');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dog', array(
             'local' => 'id',
             'foreign' => 'breed_id'));
    }
}