<?php

/**
 * BaseDog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $photo
 * @property enum $gender
 * @property timestamp $birthday
 * @property integer $user_id
 * @property integer $breed_id
 * @property User $User
 * @property Breed $Breed
 * @property Doctrine_Collection $Appointment
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getPhoto()       Returns the current record's "photo" value
 * @method enum                getGender()      Returns the current record's "gender" value
 * @method timestamp           getBirthday()    Returns the current record's "birthday" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getBreedId()     Returns the current record's "breed_id" value
 * @method User                getUser()        Returns the current record's "User" value
 * @method Breed               getBreed()       Returns the current record's "Breed" value
 * @method Doctrine_Collection getAppointment() Returns the current record's "Appointment" collection
 * @method Dog                 setId()          Sets the current record's "id" value
 * @method Dog                 setName()        Sets the current record's "name" value
 * @method Dog                 setPhoto()       Sets the current record's "photo" value
 * @method Dog                 setGender()      Sets the current record's "gender" value
 * @method Dog                 setBirthday()    Sets the current record's "birthday" value
 * @method Dog                 setUserId()      Sets the current record's "user_id" value
 * @method Dog                 setBreedId()     Sets the current record's "breed_id" value
 * @method Dog                 setUser()        Sets the current record's "User" value
 * @method Dog                 setBreed()       Sets the current record's "Breed" value
 * @method Dog                 setAppointment() Sets the current record's "Appointment" collection
 * 
 * @package    petgroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dog');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('gender', 'enum', 6, array(
             'type' => 'enum',
             'length' => 6,
             'values' => 
             array(
              0 => 'Male',
              1 => 'Female',
             ),
             ));
        $this->hasColumn('birthday', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('breed_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Breed', array(
             'local' => 'breed_id',
             'foreign' => 'id'));

        $this->hasMany('Appointment', array(
             'local' => 'id',
             'foreign' => 'dog_id'));
    }
}