<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/11 14:10:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=petgroom',
  'username' => 'root',
  'password' => 'lorilori',
  'name' => 'doctrine',
)),);
